name: Build Kernel - Default

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Making the Environment leaner
      run: sudo snap list && sudo snap remove firefox && sudo apt remove -y snapd

    - name: Update Environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg build-essential zip \
        curl libarchive-tools flex \
        unzip python3 python3-pip python3-dev \
        python-is-python3 ccache libncurses5-dev lzop \
        patchelf git-lfs ripgrep &> /dev/null

    - name: Kernel Packaging Script
      run: |
        git clone --depth=1 -b kernel_4.19.325-packaging https://github.com/DarkS1di/kernel_packaging.git packaging/packaging

    - name: Kernel Packaging Version
      run: |
        git clone --depth=1 -b kernel_4.19.325 https://github.com/DarkS1di/kernel_packaging_version.git packaging/version

    - name: Set up Clang
      run: |
        chmod +x clang.sh
        ./clang.sh

    - name: Build Kernel
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Kernel Packaging Version Move
      run: |
        cp "packaging/version/default/version" "packaging/packaging/AnyKernel3"

    - name: Package Kernel
      run: |
        ZIP_NAME=electro-kernel_v4.19.325-default-$(date +"%d.%m.%Y-%H%M%S").zip
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

        cp -r packaging/packaging/AnyKernel3 .
        chmod +x packaging/packaging/pack.sh
        bash packaging/packaging/pack.sh out/arch/arm64/boot/Image $ZIP_NAME

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: electro-kernel_v4.19.325-default
        path: ${{ env.ZIP_NAME }}
