name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set Kernel Tag
      run: |
        BRANCH_NAME="${{ github.ref_name }}"

        if [ "$BRANCH_NAME" == "electro-4.19.325-ksu_next-susfs" ]; then
          TAG="ksu_next-susfs"
        elif [ "$BRANCH_NAME" == "electro-4.19.325-ksu_next" ]; then
          TAG="ksu_next"
        else
          TAG="default"
        fi

        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Print Tag
      run: echo "Kernel tag is ${{ env.TAG }}"

    - name: Making the Environment leaner
      run: sudo snap list && sudo snap remove firefox && sudo apt remove -y snapd

    - name: Update Environment
      run: sudo apt update -y

    - name: Install Dependencies
      run: |
        sudo apt install -y git-core gnupg build-essential zip \
        curl libarchive-tools flex \
        unzip python3 python3-pip python3-dev \
        python-is-python3 ccache libncurses5-dev lzop \
        patchelf git-lfs ripgrep &> /dev/null

    - name: Kernel Packaging Script
      run: |
        git clone --depth=1 -b kernel_4.19.325-packaging https://github.com/DarkS1di/kernel_packaging.git packaging/packaging

    - name: Kernel Packaging Version
      run: |
        git clone --depth=1 -b kernel_4.19.325 https://github.com/DarkS1di/kernel_packaging_version.git packaging/version

    - name: SuSFS Patches
      if: env.TAG == 'ksu_next-susfs'
      run: |
        git clone --depth=1 -b main https://github.com/DarkS1di/susfs-kernel-4.19.git patches/susfs

    - name: Set up Clang
      run: |
        chmod +x clang.sh
        ./clang.sh

    - name: Apply SuSFS Patches
      if: env.TAG == 'ksu_next-susfs'
      run: |
        set -e

        export KERNEL_ROOT=$GITHUB_WORKSPACE

        echo "Apply SuSFS Patches..."
        cp ./patches/susfs/kernel_patches/50_add_susfs_in_kernel-4.19.patch $KERNEL_ROOT/

        cp ./patches/susfs/kernel_patches/fs/* $KERNEL_ROOT/fs/
        cp ./patches/susfs/kernel_patches/include/linux/* $KERNEL_ROOT/include/linux/

        cd $KERNEL_ROOT
        patch -p1 --verbose < 50_add_susfs_in_kernel-4.19.patch

        echo "SuSFS Patches Applied Successfully"

    - name: KernelSU Next
      if: env.TAG == 'ksu_next'
      run: | 
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -

    - name: KernelSU Next SuSFS
      if: env.TAG == 'ksu_next-susfs'
      run: | 
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Build Kernel
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Kernel Packaging Version Move
      run: |
        cp "packaging/version/${{ env.TAG }}/version" "packaging/packaging/AnyKernel3"

    - name: Package Kernel
      run: |
        ZIP_NAME=electro-kernel_v4.19.325-${{ env.TAG }}-$(date +"%d.%m.%Y-%H%M%S").zip
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

        cp -r packaging/packaging/AnyKernel3 .
        chmod +x packaging/packaging/pack.sh
        bash packaging/packaging/pack.sh out/arch/arm64/boot/Image $ZIP_NAME

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: electro-kernel_v4.19.325-${{ env.TAG }}
        path: ${{ env.ZIP_NAME }}
