name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  update_kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set branch environment
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Configure git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Add stable kernel remote
        run: |
          git remote add stable https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git || true
          git fetch stable linux-4.19.y

      - name: Checkout current branch
        run: git checkout $BRANCH_NAME

      - name: Merge stable 4.19.y
        run: |
          git merge --no-edit --ff stable/linux-4.19.y || true

      - name: Commit auto-merged changes
        run: |
          git add -A

          if ! git diff --cached --quiet; then
            echo "Committing auto-merged changes..."
            git commit -s -m "Auto-merge changes from stable/linux-4.19.y"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        run: git push origin $BRANCH_NAME
